const express = require('express');
const cors = require('cors');
const bodyParser = require('body-parser');

const app = express();
app.use(cors());
app.use(bodyParser.json());

//Memory Saved Data - Saved as JSON for easier accesibility.
let data = [
    {"id": 1, "name": "Nina", "age": 35, "gender": "Female", "job": "Librarian"},
{"id": 2, "name": "Nina", "age": 50, "gender": "Male", "job": "Chef"},
{"id": 3, "name": "Jane", "age": 61, "gender": "Male", "job": "Nurse"},
{"id": 4, "name": "Bob", "age": 18, "gender": "Female", "job": "HR Specialist"},
{"id": 5, "name": "Vince", "age": 55, "gender": "Male", "job": "Librarian"},
{"id": 6, "name": "Bob", "age": 57, "gender": "Female", "job": "Logistician"},
{"id": 7, "name": "Zach", "age": 51, "gender": "Female", "job": "Financial Analyst"},
{"id": 8, "name": "Iris", "age": 35, "gender": "Female", "job": "Pharmacist"},
{"id": 9, "name": "Laura", "age": 21, "gender": "Male", "job": "Designer"},
{"id": 10, "name": "Paula", "age": 44, "gender": "Male", "job": "Logistician"},
{"id": 11, "name": "Hannah", "age": 62, "gender": "Male", "job": "Architect"},
{"id": 12, "name": "Kyle", "age": 41, "gender": "Female", "job": "Yoga Instructor"},
{"id": 13, "name": "Mia", "age": 28, "gender": "Female", "job": "Librarian"},
{"id": 14, "name": "Nina", "age": 29, "gender": "Female", "job": "Operations Manager"},
{"id": 15, "name": "Doug", "age": 43, "gender": "Female", "job": "Yoga Instructor"},
{"id": 16, "name": "Amy", "age": 28, "gender": "Female", "job": "Lawyer"},
{"id": 17, "name": "Brian", "age": 28, "gender": "Male", "job": "Veterinarian"},
{"id": 18, "name": "Brian", "age": 58, "gender": "Female", "job": "Nutritionist"},
{"id": 19, "name": "Alice", "age": 44, "gender": "Male", "job": "Accountant"},
{"id": 20, "name": "Nate", "age": 65, "gender": "Male", "job": "Veterinarian"},
{"id": 21, "name": "Will", "age": 29, "gender": "Female", "job": "Musician"},
{"id": 22, "name": "Bob", "age": 65, "gender": "Female", "job": "Ecologist"},
{"id": 23, "name": "Tom", "age": 63, "gender": "Female", "job": "Writer"},
{"id": 24, "name": "Paula", "age": 22, "gender": "Female", "job": "Urologist"},
{"id": 25, "name": "Rob", "age": 38, "gender": "Female", "job": "Doctor"},
{"id": 26, "name": "Uma", "age": 34, "gender": "Female", "job": "Therapist"},
{"id": 27, "name": "Jane", "age": 45, "gender": "Female", "job": "Scientist"},
{"id": 28, "name": "Rob", "age": 26, "gender": "Male", "job": "Graphic Designer"},
{"id": 29, "name": "Ella", "age": 26, "gender": "Male", "job": "Scientist"},
{"id": 30, "name": "Nate", "age": 40, "gender": "Female", "job": "Designer"},
{"id": 31, "name": "Iris", "age": 51, "gender": "Male", "job": "Urologist"},
{"id": 32, "name": "Laura", "age": 42, "gender": "Male", "job": "Surgeon"},
{"id": 33, "name": "Zoe", "age": 48, "gender": "Male", "job": "Nutritionist"},
{"id": 34, "name": "Ursula", "age": 49, "gender": "Male", "job": "Dentist"},
{"id": 35, "name": "Queen", "age": 55, "gender": "Female", "job": "Police Officer"},
{"id": 36, "name": "Quinn", "age": 38, "gender": "Male", "job": "HR Specialist"},
{"id": 37, "name": "Cathy", "age": 59, "gender": "Female", "job": "Architect"},
{"id": 38, "name": "Leo", "age": 48, "gender": "Female", "job": "Teacher"},
{"id": 39, "name": "Jack", "age": 58, "gender": "Male", "job": "Pharmacist"},
{"id": 40, "name": "Gina", "age": 23, "gender": "Female", "job": "Geologist"},
{"id": 41, "name": "Tina", "age": 61, "gender": "Female", "job": "Veterinarian"},
{"id": 42, "name": "Tina", "age": 23, "gender": "Female", "job": "Insurance Agent"},
{"id": 43, "name": "Ian", "age": 42, "gender": "Female", "job": "Lawyer"},
{"id": 44, "name": "Frank", "age": 21, "gender": "Female", "job": "Quality Control Inspector"},
{"id": 45, "name": "Zoe", "age": 27, "gender": "Female", "job": "Artist"},
{"id": 46, "name": "Will", "age": 50, "gender": "Female", "job": "X-ray Technician"},
{"id": 47, "name": "Fred", "age": 21, "gender": "Female", "job": "Historian"},
{"id": 48, "name": "Henry", "age": 29, "gender": "Male", "job": "Radiologist"},
{"id": 49, "name": "Hannah", "age": 19, "gender": "Male", "job": "Navy Officer"},
{"id": 50, "name": "Olivia", "age": 65, "gender": "Male", "job": "Judge"},
{"id": 51, "name": "Cathy", "age": 41, "gender": "Male", "job": "Farmer"},
{"id": 52, "name": "Brian", "age": 61, "gender": "Male", "job": "Therapist"},
{"id": 53, "name": "Jack", "age": 50, "gender": "Female", "job": "Police Officer"},
{"id": 54, "name": "David", "age": 59, "gender": "Male", "job": "Graphic Designer"},
{"id": 55, "name": "Brian", "age": 26, "gender": "Male", "job": "Kindergarten Teacher"},
{"id": 56, "name": "Pete", "age": 26, "gender": "Male", "job": "Scientist"},
{"id": 57, "name": "Mia", "age": 25, "gender": "Female", "job": "Doctor"},
{"id": 58, "name": "Tina", "age": 28, "gender": "Male", "job": "Dentist"},
{"id": 59, "name": "Tina", "age": 40, "gender": "Male", "job": "Historian"},
{"id": 60, "name": "Cathy", "age": 44, "gender": "Female", "job": "Designer"},
{"id": 61, "name": "Paula", "age": 55, "gender": "Male", "job": "Doctor"},
{"id": 62, "name": "Alice", "age": 18, "gender": "Male", "job": "Navy Officer"},
{"id": 63, "name": "Victor", "age": 36, "gender": "Male", "job": "Judge"},
{"id": 64, "name": "Tom", "age": 34, "gender": "Male", "job": "Designer"},
{"id": 65, "name": "Frank", "age": 48, "gender": "Male", "job": "Surgeon"},
{"id": 66, "name": "Eva", "age": 50, "gender": "Female", "job": "Doctor"},
{"id": 67, "name": "Fred", "age": 55, "gender": "Male", "job": "Artist"},
{"id": 68, "name": "Fred", "age": 64, "gender": "Male", "job": "Ecologist"},
{"id": 69, "name": "Doug", "age": 40, "gender": "Female", "job": "Logistician"},
{"id": 70, "name": "Mia", "age": 22, "gender": "Female", "job": "Zoologist"},
{"id": 71, "name": "Laura", "age": 43, "gender": "Female", "job": "Graphic Designer"},
{"id": 72, "name": "Xander", "age": 36, "gender": "Male", "job": "Veterinarian"},
{"id": 73, "name": "Gina", "age": 45, "gender": "Male", "job": "Chef"},
{"id": 74, "name": "Fred", "age": 32, "gender": "Female", "job": "Quality Control Inspector"},
{"id": 75, "name": "Sara", "age": 43, "gender": "Male", "job": "Nurse"},
{"id": 76, "name": "Victor", "age": 40, "gender": "Male", "job": "Mechanic"},
{"id": 77, "name": "Doug", "age": 21, "gender": "Male", "job": "Farmer"},
{"id": 78, "name": "Alice", "age": 35, "gender": "Female", "job": "X-ray Technician"},
{"id": 79, "name": "Doug", "age": 25, "gender": "Male", "job": "Lawyer"},
{"id": 80, "name": "Frank", "age": 30, "gender": "Female", "job": "Optometrist"},
{"id": 81, "name": "Tina", "age": 50, "gender": "Female", "job": "Engineer"},
{"id": 82, "name": "Doug", "age": 28, "gender": "Male", "job": "Teacher"},
{"id": 83, "name": "Jack", "age": 44, "gender": "Female", "job": "Judge"},
{"id": 84, "name": "Vince", "age": 18, "gender": "Female", "job": "Mechanic"},
{"id": 85, "name": "Hannah", "age": 36, "gender": "Female", "job": "Doctor"},
{"id": 86, "name": "Charlie", "age": 65, "gender": "Female", "job": "Geologist"},
{"id": 87, "name": "Paula", "age": 57, "gender": "Female", "job": "Logistician"},
{"id": 88, "name": "Paula", "age": 24, "gender": "Female", "job": "Electrician"},
{"id": 89, "name": "Kyle", "age": 36, "gender": "Female", "job": "Interpreter"},
{"id": 90, "name": "Will", "age": 52, "gender": "Female", "job": "Web Developer"},
{"id": 91, "name": "Cathy", "age": 36, "gender": "Female", "job": "Insurance Agent"},
{"id": 92, "name": "Cathy", "age": 38, "gender": "Female", "job": "Quality Control Inspector"},
{"id": 93, "name": "Paula", "age": 49, "gender": "Female", "job": "Urologist"},
{"id": 94, "name": "Ursula", "age": 29, "gender": "Male", "job": "Librarian"},
{"id": 95, "name": "Zach", "age": 57, "gender": "Female", "job": "Surgeon"},
{"id": 96, "name": "Will", "age": 31, "gender": "Female", "job": "Musician"},
{"id": 97, "name": "Kyle", "age": 60, "gender": "Male", "job": "Chemist"},
{"id": 98, "name": "Doug", "age": 50, "gender": "Female", "job": "Optometrist"},
{"id": 99, "name": "Quinn", "age": 55, "gender": "Male", "job": "Accountant"},
{"id": 100, "name": "Yara", "age": 21, "gender": "Female", "job": "Historian"},
{"id": 101, "name": "Jane", "age": 56, "gender": "Male", "job": "Chef"},
{"id": 102, "name": "Olivia", "age": 41, "gender": "Female", "job": "Insurance Agent"},
{"id": 103, "name": "Uma", "age": 44, "gender": "Female", "job": "Accountant"},
{"id": 104, "name": "Olivia", "age": 33, "gender": "Male", "job": "Teacher"},
{"id": 105, "name": "Steve", "age": 48, "gender": "Male", "job": "Geologist"},
{"id": 106, "name": "Frank", "age": 26, "gender": "Female", "job": "Architect"},
{"id": 107, "name": "Pete", "age": 33, "gender": "Female", "job": "Therapist"},
{"id": 108, "name": "Eva", "age": 60, "gender": "Female", "job": "Kindergarten Teacher"},
{"id": 109, "name": "Will", "age": 27, "gender": "Female", "job": "Chemist"},
{"id": 110, "name": "Yara", "age": 25, "gender": "Female", "job": "Kindergarten Teacher"},
{"id": 111, "name": "Yara", "age": 27, "gender": "Male", "job": "Engineer"},
{"id": 112, "name": "Victor", "age": 55, "gender": "Female", "job": "Chemist"},
{"id": 113, "name": "Vince", "age": 49, "gender": "Female", "job": "Artist"},
{"id": 114, "name": "Nina", "age": 60, "gender": "Male", "job": "Musician"},
{"id": 115, "name": "Ella", "age": 21, "gender": "Female", "job": "Engineer"},
{"id": 116, "name": "Vince", "age": 63, "gender": "Male", "job": "Scientist"},
{"id": 117, "name": "Uma", "age": 40, "gender": "Male", "job": "Artist"},
{"id": 118, "name": "Zoe", "age": 51, "gender": "Female", "job": "Nutritionist"},
{"id": 119, "name": "Leo", "age": 56, "gender": "Female", "job": "Accountant"},
{"id": 120, "name": "Fred", "age": 27, "gender": "Female", "job": "Navy Officer"},
{"id": 121, "name": "Cathy", "age": 60, "gender": "Female", "job": "Radiologist"},
{"id": 122, "name": "Doug", "age": 57, "gender": "Male", "job": "Electrician"},
{"id": 123, "name": "Brian", "age": 50, "gender": "Male", "job": "Scientist"},
{"id": 124, "name": "Laura", "age": 18, "gender": "Female", "job": "Yoga Instructor"},
{"id": 125, "name": "Charlie", "age": 49, "gender": "Female", "job": "Historian"},
{"id": 126, "name": "Tina", "age": 58, "gender": "Male", "job": "Pharmacist"},
{"id": 127, "name": "Mia", "age": 19, "gender": "Female", "job": "Chef"},
{"id": 128, "name": "Hannah", "age": 33, "gender": "Female", "job": "Quality Control Inspector"},
{"id": 129, "name": "Jane", "age": 18, "gender": "Female", "job": "Financial Analyst"},
{"id": 130, "name": "Olivia", "age": 23, "gender": "Female", "job": "Graphic Designer"},
{"id": 131, "name": "Sara", "age": 29, "gender": "Female", "job": "Designer"},
{"id": 132, "name": "Xander", "age": 22, "gender": "Male", "job": "Nurse"},
{"id": 133, "name": "Zoe", "age": 59, "gender": "Male", "job": "Urologist"},
{"id": 134, "name": "Tina", "age": 63, "gender": "Female", "job": "Navy Officer"},
{"id": 135, "name": "Alice", "age": 50, "gender": "Female", "job": "Financial Analyst"},
{"id": 136, "name": "Mia", "age": 49, "gender": "Female", "job": "Writer"},
{"id": 137, "name": "Ella", "age": 21, "gender": "Male", "job": "Farmer"},
{"id": 138, "name": "Rachel", "age": 29, "gender": "Female", "job": "Nurse"},
{"id": 139, "name": "Charlie", "age": 56, "gender": "Male", "job": "Zoologist"},
{"id": 140, "name": "Wendy", "age": 50, "gender": "Female", "job": "Farmer"},
{"id": 141, "name": "Leo", "age": 23, "gender": "Female", "job": "Doctor"},
{"id": 142, "name": "Will", "age": 62, "gender": "Female", "job": "Quantity Surveyor"},
{"id": 143, "name": "Uma", "age": 35, "gender": "Female", "job": "Zoologist"},
{"id": 144, "name": "Eva", "age": 55, "gender": "Female", "job": "Judge"},
{"id": 145, "name": "Kyle", "age": 21, "gender": "Female", "job": "Insurance Agent"},
{"id": 146, "name": "Charlie", "age": 18, "gender": "Female", "job": "Quantity Surveyor"},
{"id": 147, "name": "Brian", "age": 56, "gender": "Female", "job": "Musician"},
{"id": 148, "name": "Victor", "age": 47, "gender": "Female", "job": "Radiologist"},
{"id": 149, "name": "Doug", "age": 38, "gender": "Female", "job": "Accountant"},
{"id": 150, "name": "Eva", "age": 33, "gender": "Male", "job": "Operations Manager"},
{"id": 151, "name": "Amy", "age": 41, "gender": "Male", "job": "Radiologist"},
{"id": 152, "name": "Hannah", "age": 64, "gender": "Female", "job": "Interpreter"},
{"id": 153, "name": "Rob", "age": 20, "gender": "Female", "job": "Pharmacist"},
{"id": 154, "name": "Zoe", "age": 48, "gender": "Male", "job": "Scientist"},
{"id": 155, "name": "Uma", "age": 56, "gender": "Male", "job": "Writer"},
{"id": 156, "name": "Pete", "age": 53, "gender": "Male", "job": "Designer"},
{"id": 157, "name": "Victor", "age": 50, "gender": "Female", "job": "Urologist"},
{"id": 158, "name": "Bob", "age": 20, "gender": "Male", "job": "Marketing Manager"},
{"id": 159, "name": "Ian", "age": 49, "gender": "Female", "job": "Nutritionist"},
{"id": 160, "name": "Rob", "age": 20, "gender": "Female", "job": "Lawyer"},
{"id": 161, "name": "Ella", "age": 59, "gender": "Female", "job": "Zoologist"},
{"id": 162, "name": "Alice", "age": 34, "gender": "Female", "job": "Urologist"},
{"id": 163, "name": "Iris", "age": 24, "gender": "Female", "job": "Veterinarian"},
{"id": 164, "name": "Leo", "age": 19, "gender": "Male", "job": "Architect"},
{"id": 165, "name": "Eva", "age": 35, "gender": "Female", "job": "Designer"},
{"id": 166, "name": "Jack", "age": 43, "gender": "Male", "job": "Nurse"},
{"id": 167, "name": "Laura", "age": 63, "gender": "Female", "job": "Yoga Instructor"},
{"id": 168, "name": "Grace", "age": 24, "gender": "Male", "job": "Kindergarten Teacher"},
{"id": 169, "name": "Eva", "age": 60, "gender": "Male", "job": "Police Officer"},
{"id": 170, "name": "Quinn", "age": 61, "gender": "Male", "job": "Insurance Agent"},
{"id": 171, "name": "Henry", "age": 52, "gender": "Male", "job": "Teacher"},
{"id": 172, "name": "Bob", "age": 25, "gender": "Female", "job": "Veterinarian"},
{"id": 173, "name": "Paula", "age": 39, "gender": "Female", "job": "HR Specialist"},
{"id": 174, "name": "Uma", "age": 46, "gender": "Male", "job": "Lawyer"},
{"id": 175, "name": "Fred", "age": 27, "gender": "Male", "job": "Electrician"},
{"id": 176, "name": "Vince", "age": 48, "gender": "Female", "job": "Librarian"},
{"id": 177, "name": "Henry", "age": 40, "gender": "Female", "job": "Designer"},
{"id": 178, "name": "Henry", "age": 63, "gender": "Male", "job": "Chemist"},
{"id": 179, "name": "Leo", "age": 61, "gender": "Male", "job": "X-ray Technician"},
{"id": 180, "name": "Henry", "age": 50, "gender": "Male", "job": "Interpreter"},
{"id": 181, "name": "Ian", "age": 49, "gender": "Male", "job": "Accountant"},
{"id": 182, "name": "Zoe", "age": 23, "gender": "Male", "job": "Quality Control Inspector"},
{"id": 183, "name": "Rob", "age": 39, "gender": "Female", "job": "Quantity Surveyor"},
{"id": 184, "name": "Will", "age": 33, "gender": "Male", "job": "Optometrist"},
{"id": 185, "name": "Olivia", "age": 25, "gender": "Female", "job": "Pharmacist"},
{"id": 186, "name": "Will", "age": 47, "gender": "Male", "job": "Lawyer"},
{"id": 187, "name": "Iris", "age": 43, "gender": "Male", "job": "Journalist"},
{"id": 188, "name": "Nate", "age": 33, "gender": "Female", "job": "Doctor"},
{"id": 189, "name": "Cathy", "age": 58, "gender": "Female", "job": "Accountant"},
{"id": 190, "name": "Kara", "age": 62, "gender": "Male", "job": "Interpreter"},
{"id": 191, "name": "Jane", "age": 25, "gender": "Male", "job": "Police Officer"},
{"id": 192, "name": "Olivia", "age": 56, "gender": "Male", "job": "Doctor"},
{"id": 193, "name": "Paula", "age": 35, "gender": "Male", "job": "Logistician"},
{"id": 194, "name": "Vince", "age": 44, "gender": "Female", "job": "Writer"},
{"id": 195, "name": "Wendy", "age": 21, "gender": "Female", "job": "Judge"},
{"id": 196, "name": "Paula", "age": 37, "gender": "Male", "job": "Teacher"},
{"id": 197, "name": "Fred", "age": 51, "gender": "Male", "job": "Judge"},
{"id": 198, "name": "Charlie", "age": 27, "gender": "Female", "job": "Farmer"},
{"id": 199, "name": "Hannah", "age": 28, "gender": "Female", "job": "Chef"},
{"id": 200, "name": "Nina", "age": 57, "gender": "Male", "job": "Doctor"},

]


//API Routes
app.get('/api/records', (req,res) => {
    //Fetching and returning all the data stored.
    res.json(data);
});

app.post('/api/records', (req, res) => {
    //Adds a new record
    const newRecord = req.body;
    data.push(newRecord);
    res.status(201).json(newRecord);
    console.log(newRecord);
});

app.put('/api/records/:id', (req,res) => {
    //Updates a new record using the id as a param
    const id = parseInt(req.params.id);
    console.log(`ID: ${id} - ${typeof(id)}`);
    const updatedRecord = req.body;
    data = data.map(record => (record.id === id ? updatedRecord : record));
    res.json(updatedRecord);
});

app.delete('/api/records/:id', (req,res) => {
    //Deletes an already existing record using the id as a param
    const id = parseInt(req.params.id);
    console.log(`${id} - ${typeof(id)}`);
    data = data.filter(record => record.id !== id);
    res.status(204).end();
})

const PORT = process.env.PORT || 5000;
app.listen(PORT, () => console.log('Server running on port 5000'));
